In [10]:
import tensorflow as tf
import numpy as np
from cake.kernels import s_gaussian_mlp1
tf_float_type = tf.float64

In [11]:
n_p = 5
n_q = 3
d = 2
x_p = np.random.rand(n_p, d)
x_q = np.random.rand(n_q, d)
tf_x_p = tf.Variable(x_p)
tf_x_q = tf.Variable(x_q)

In [12]:
d_1 = 5
d_2 = 4
w_1 = np.random.rand(d, d_1)
b_1 = np.random.rand(d_1)
theta = np.array([1., 1.])
zeta = 1e-4
tf_w_1 = tf.Variable(w_1)
tf_b_1 = tf.Variable(b_1)
tf_theta = tf.Variable(theta)
tf_zeta = tf.Variable(zeta)

In [13]:
tf_k = s_gaussian_mlp1(tf_x_p, tf_x_p, tf_theta, tf_w_1, tf_b_1)

i = tf.cast(tf.eye(n_p), tf_float_type)
reg = n_p * zeta * i
        
tf_k_reg = tf_k + reg
tf_l = tf.cholesky(tf_k_reg)

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(tf_k))
print(sess.run(tf_k_reg))
print(sess.run(tf_l))

[[ 1.          0.82237829  0.85007807  0.87604647  0.90431896]
 [ 0.82237829  1.          0.81137635  0.58266935  0.5621686 ]
 [ 0.85007807  0.81137635  1.          0.83912688  0.70208994]
 [ 0.87604647  0.58266935  0.83912688  1.          0.93314274]
 [ 0.90431896  0.5621686   0.70208994  0.93314274  1.        ]]
[[ 1.0005      0.82237829  0.85007807  0.87604647  0.90431896]
 [ 0.82237829  1.0005      0.81137635  0.58266935  0.5621686 ]
 [ 0.85007807  0.81137635  1.0005      0.83912688  0.70208994]
 [ 0.87604647  0.58266935  0.83912688  1.0005      0.93314274]
 [ 0.90431896  0.5621686   0.70208994  0.93314274  1.0005    ]]
[[ 1.00024997  0.          0.          0.          0.        ]
 [ 0.82217278  0.56967704  0.          0.          0.        ]
 [ 0.84986563  0.197726    0.4890121   0.          0.        ]
 [ 0.87582754 -0.24121073  0.29137271  0.30057518  0.        ]
 [ 0.90409296 -0.31799074 -0.00693756  0.22168118  0.18112739]]
