In [1]:
import numpy as np
import bake
np.set_printoptions(2)

In [2]:
X = np.array([[-1, 1], [1, 1], [0, 0], [-1, -1], [1, -1]])
I = np.eye(X.shape[0])
print(X)

[[-1  1]
 [ 1  1]
 [ 0  0]
 [-1 -1]
 [ 1 -1]]


In [3]:
kernel = bake.kernels.gaussian
k = lambda s, t: (s ** 2) * kernel(X, X, t)
w = lambda s, t, l: bake.linalg.solve_posdef(k(s, t) + (l ** 2) * I, k(s, t))[0]

In [4]:
def print_w_info(s, t, l):
    W = w(s, t, l)
    return print(W, W.sum(axis=0), np.round(W.diagonal().sum(), 4), np.round(W.T.dot(W).diagonal().sum(), 4))

In [5]:
# Increasing length scale increases off-diagonal entries (points affect each other more)
# Eventually the diagonal entries also drop off (self becomes less important)
# It does not really affect the sum of weights
[print_w_info(1, t, 0.01) for t in [0.1, 1, 10, 100, 1000]]

[[  1.00e+00   1.38e-95   3.72e-48   1.38e-95  -1.38e-91]
 [  1.38e-95   1.00e+00   3.72e-48  -1.38e-91   1.38e-95]
 [  3.72e-48   3.72e-48   1.00e+00   3.72e-48   3.72e-48]
 [  1.38e-95  -1.38e-91   3.72e-48   1.00e+00   1.38e-95]
 [ -1.38e-91   1.38e-95   3.72e-48   1.38e-95   1.00e+00]] [ 1.  1.  1.  1.  1.] 4.9995 4.999
[[  1.00e+00   2.42e-09   4.92e-05   2.42e-09  -1.59e-05]
 [  2.42e-09   1.00e+00   4.92e-05  -1.59e-05   2.42e-09]
 [  4.92e-05   4.92e-05   1.00e+00   4.92e-05   4.92e-05]
 [  2.42e-09  -1.59e-05   4.92e-05   1.00e+00   2.42e-09]
 [ -1.59e-05   2.42e-09   4.92e-05   2.42e-09   1.00e+00]] [ 1.  1.  1.  1.  1.] 4.9994 4.9987
[[ 0.92  0.02  0.11  0.02 -0.08]
 [ 0.02  0.92  0.11 -0.08  0.02]
 [ 0.11  0.11  0.56  0.11  0.11]
 [ 0.02 -0.08  0.11  0.92  0.02]
 [-0.08  0.02  0.11  0.02  0.92]] [ 1.  1.  1.  1.  1.] 4.2351 3.8213
[[ 0.6  0.2  0.2  0.2 -0.2]
 [ 0.2  0.6  0.2 -0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2 -0.2  0.2  0.6  0.2]
 [-0.2  0.2  0.2  0.2  0.6]] [ 1.

[None, None, None, None, None]

In [6]:
# Increasing regularisation decreases diagonal entries (self becomes less important) and 
# increases off-diagonal entries (points affect each other more)
# Diagonal entries seem to max out at 1
[print_w_info(1, 1, l) for l in [1e-8, 1e-6, 1e-4, 1e-2, 1e-1, 1]]

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]] [ 1.  1.  1.  1.  1.] 5.0 5.0
[[  1.00e+00   0.00e+00   4.92e-13   1.60e-17  -1.59e-13]
 [ -2.26e-17   1.00e+00   4.92e-13  -1.59e-13  -1.29e-17]
 [  4.92e-13   4.92e-13   1.00e+00   4.92e-13   4.92e-13]
 [ -2.26e-17  -1.59e-13   4.92e-13   1.00e+00  -3.27e-17]
 [ -1.59e-13  -3.27e-17   4.92e-13   0.00e+00   1.00e+00]] [ 1.  1.  1.  1.  1.] 5.0 5.0
[[  1.00e+00   2.78e-17   4.92e-09   3.09e-17  -1.59e-09]
 [  2.14e-17   1.00e+00   4.92e-09  -1.59e-09   1.18e-17]
 [  4.92e-09   4.92e-09   1.00e+00   4.92e-09   4.92e-09]
 [  2.14e-17  -1.59e-09   4.92e-09   1.00e+00  -8.49e-18]
 [ -1.59e-09   3.27e-17   4.92e-09   3.27e-17   1.00e+00]] [ 1.  1.  1.  1.  1.] 5.0 5.0
[[  1.00e+00   2.42e-09   4.92e-05   2.42e-09  -1.59e-05]
 [  2.42e-09   1.00e+00   4.92e-05  -1.59e-05   2.42e-09]
 [  4.92e-05   4.92e-05   1.00e+00   4.92e-05   4.92e-05]
 [  2.42e-09  -1.59e-05   4.92e-05   1

[None, None, None, None, None, None]

In [7]:
# Increasing sensitivity increases diagonal entries (self becomes more important) and 
# decreases off-diagonal entries (points affect each other less)
# Seems to be opposite to regularisation parameter
# Diagonal entries seem to max out at 1
[print_w_info(s, 1, 0.01) for s in [1e-3, 1e-2, 1, 1e2, 1e4, 1e6]]

[[ 0.01  0.    0.    0.    0.  ]
 [ 0.    0.01  0.    0.    0.  ]
 [ 0.    0.    0.01  0.    0.  ]
 [ 0.    0.    0.    0.01  0.  ]
 [ 0.    0.    0.    0.    0.01]] [ 0.02  0.02  0.02  0.02  0.02] 0.0494 0.0006
[[ 0.48  0.02  0.09  0.02 -0.01]
 [ 0.02  0.48  0.09 -0.01  0.02]
 [ 0.09  0.09  0.43  0.09  0.09]
 [ 0.02 -0.01  0.09  0.48  0.02]
 [-0.01  0.02  0.09  0.02  0.48]] [ 0.6  0.6  0.8  0.6  0.6] 2.356 1.1823
[[  1.00e+00   2.42e-09   4.92e-05   2.42e-09  -1.59e-05]
 [  2.42e-09   1.00e+00   4.92e-05  -1.59e-05   2.42e-09]
 [  4.92e-05   4.92e-05   1.00e+00   4.92e-05   4.92e-05]
 [  2.42e-09  -1.59e-05   4.92e-05   1.00e+00   2.42e-09]
 [ -1.59e-05   2.42e-09   4.92e-05   2.42e-09   1.00e+00]] [ 1.  1.  1.  1.  1.] 4.9994 4.9987
[[  1.00e+00   3.55e-17   4.92e-09   2.01e-17  -1.59e-09]
 [  1.53e-17   1.00e+00   4.92e-09  -1.59e-09   1.36e-17]
 [  4.92e-09   4.92e-09   1.00e+00   4.92e-09   4.92e-09]
 [  1.53e-17  -1.59e-09   4.92e-09   1.00e+00   2.42e-17]
 [ -1.59e-09   2.68e-17

[None, None, None, None, None, None]