In [16]:
import numpy as np
np.set_printoptions(2)
np.random.seed(0)

In [17]:
def rvs(dim=3):
     random_state = np.random
     H = np.eye(dim)
     D = np.ones((dim,))
     for n in range(1, dim):
         x = random_state.normal(size=(dim-n+1,))
         D[n-1] = np.sign(x[0])
         x[0] -= D[n-1]*np.sqrt((x*x).sum())
         # Householder transformation
         Hx = (np.eye(dim-n+1) - 2.*np.outer(x, x)/(x*x).sum())
         mat = np.eye(dim)
         mat[n-1:, n-1:] = Hx
         H = np.dot(H, mat)
         # Fix the last sign such that the determinant is 1
     D[-1] = (-1)**(1-(dim % 2))*D.prod()
     # Equivalent to np.dot(np.diag(D), H) but faster, apparently
     H = (D*H.T).T
     return H

In [18]:
U = rvs(dim=5)
U = U[:, :2]

In [19]:
U

array([[ 0.49, -0.  ],
       [-0.11, -0.71],
       [ 0.27, -0.69],
       [ 0.63,  0.11],
       [-0.52, -0.08]])

In [20]:
V = rvs(dim=3)
V = V[:, :2]

In [21]:
V

array([[ 0.28, -0.67],
       [-0.21, -0.74],
       [-0.94, -0.03]])

In [22]:
s = np.array([2, 4])

In [23]:
D = np.diag(s)

In [24]:
A = np.dot(U, np.dot(D, V.T))

In [25]:
A

array([[ 0.28, -0.2 , -0.93],
       [ 1.84,  2.16,  0.3 ],
       [ 2.  ,  1.93, -0.42],
       [ 0.05, -0.59, -1.19],
       [-0.09,  0.45,  0.99]])

In [26]:
from scipy.linalg import svd

In [27]:
u, s, vt = svd(A, full_matrices=False)

In [28]:
u

array([[-0.  , -0.49,  0.85],
       [-0.71,  0.11,  0.14],
       [-0.69, -0.27, -0.23],
       [ 0.11, -0.63, -0.43],
       [-0.08,  0.52,  0.15]])

In [29]:
s

array([  4.00e+00,   2.00e+00,   1.29e-16])

In [30]:
vt

array([[-0.67, -0.74, -0.03],
       [-0.28,  0.21,  0.94],
       [-0.69,  0.64, -0.35]])