In [1]:
import numpy as np

In [2]:
np.random.seed(0)
d = np.diag(np.random.randint(0, 10, (2,)))
u = np.random.randint(0, 10, (6, 2))
vt = np.random.randint(0, 10, (2, 4))
A = np.dot(u, np.dot(d, vt))

In [3]:
A = np.concatenate((A,))
A

array([[ 15,  90, 105, 105],
       [ 35, 210, 245, 245],
       [ 15,  90, 105, 105],
       [ 10,  60,  70,  70],
       [ 35, 210, 245, 245],
       [ 40, 240, 280, 280]])

In [4]:
from scipy.linalg import svd

In [5]:
u, s, vt = svd(A, full_matrices=False)

In [6]:
np.set_printoptions(1e-2)

In [7]:
u
u.shape

(6, 4)

In [8]:
s
s.shape

(4,)

In [9]:
vt
vt.shape

(4, 4)

In [10]:
np.dot(u, np.dot(np.diag(s), vt))

array([[  15.,   90.,  105.,  105.],
       [  35.,  210.,  245.,  245.],
       [  15.,   90.,  105.,  105.],
       [  10.,   60.,   70.,   70.],
       [  35.,  210.,  245.,  245.],
       [  40.,  240.,  280.,  280.]])

In [11]:
np.dot(A, A.T)

array([[ 30375,  70875,  30375,  20250,  70875,  81000],
       [ 70875, 165375,  70875,  47250, 165375, 189000],
       [ 30375,  70875,  30375,  20250,  70875,  81000],
       [ 20250,  47250,  20250,  13500,  47250,  54000],
       [ 70875, 165375,  70875,  47250, 165375, 189000],
       [ 81000, 189000,  81000,  54000, 189000, 216000]])

In [12]:
# Trace Norm
np.sqrt(np.trace(np.dot(A.T, A)))

788.03553219382184

In [13]:
# Trace Norm
np.sqrt(np.trace(np.dot(A, A.T)))

788.03553219382184

In [14]:
_, s, _ = svd(A)
np.sum(s)

788.03553219382218

In [15]:
s, _ = np.linalg.eig(np.dot(A.T, A))
np.sqrt(np.sum(s))

788.03553219382184

In [16]:
s, _ = np.linalg.eig(np.dot(A, A.T))
np.sqrt(np.sum(s))

(788.03553219382172+0j)